### ISSUE TITLE
Failed build --release

### ISSUE THREAD

**Issue by willisga** [RedisJSON/RedisDoc#60]
Hello, I downloaded the code of the master branch and when executing the command to compile (**cargo build --release**) I get the following error.

![Image of Subsytem Ubuntu](https://i.ibb.co/1fDXk6p/2019-09-13.png)

What should I do to compile the code and get the module for Redis?

Note: I am using the ubuntu subsystem in windows

Thanks.

**Comment by willisga** [comment]
Ok, identify each of the related errors in the terminal to build the module **libredisjson.so**, it is necessary install the following packages:


- Install Llvm
**Command Install**: `apt install llvm`

_Install_
![Img1](https://i.ibb.co/nmZ4K7w/2-Install-LLVM.png)

_Error_: This package fixes the following compilation error
![Img1](https://i.ibb.co/1fDXk6p/2019-09-13.png)

After installing, executing the `charge build --release` command generates a new error

- Install clang
**Command Install**: `apt-get install clang`

_Install_
![Img](https://i.ibb.co/w6MLz9m/5-Install-Clang.png)

_Error_: This package fixes the following compilation error
![img](https://i.ibb.co/ctWxjc2/4-Error-clang.png)

After installing, executing the `charge build --release` command generates a new error

- Install rustfmt
**Command Install**: `rustup component add rustfmt-preview`

_Install_
![Img](https://i.ibb.co/0CxPPBV/7-Install-Rustfmt.png)

_Error_: This package fixes the following compilation error
![Img](https://i.ibb.co/CnpbdNS/3-Error-Rustfmt.png)

After installing, executing the `charge build --release` command generates a new error

-  Install cmake
**Command Install**: `apt-get install cmake`

_Install_
![Img](https://i.ibb.co/tsf7qBC/9-Install-Cmake.png)

_Error_: This package fixes the following compilation error
![Img](https://i.ibb.co/8PLCWf1/8-Error-Cmake.png)

After installing those packages, you can execute the command to create the RedisJson module

_Build_
![image](https://user-images.githubusercontent.com/16823804/64885538-0efddf00-d62a-11e9-8e9f-f9170b460e0b.png)

_File_
![image](https://user-images.githubusercontent.com/16823804/64885600-30f76180-d62a-11e9-98d7-57770e8c335b.png)

To validate the installed packages, you can execute the following commands

- `llvm-config --version`
- `clang --version`
- `rustup run stable rustfmt --version`
- `cmake --version`

![image](https://user-images.githubusercontent.com/16823804/64885806-a3684180-d62a-11e9-946d-3ce2d0cd2bf7.png)

Thanks for your remarks, I shall be attentive to your criticisms or your proposals when you have had time to read this document.

**Comment by gkorland** [comment]
@willisga thanks for your feedback!
