### ISSUE TITLE
Docker image in Hub

### ISSUE THREAD

**Issue by lucax88x** [RedisJSON/RedisDoc#69]
Does it make sense to tag the 2nd version in the rejson repository?

Or it's too early to use it?

**Comment by gkorland** [comment]
The current version is pretty stable and backward compatible with RedisJSON 1.0, but it's not full yet and we plan to add couple more features first before releasing as RedisJSON 2.0.

We'll probably start to tag preview versions soon on Docker Hub

**Comment by gkorland** [comment]
https://hub.docker.com/r/redislabs/redisjson2/

**Comment by lucax88x** [comment]
Thanks!
