### ISSUE TITLE
Missing container image in registry

### ISSUE THREAD

**Issue by darkshade9** [RedisJSON/RedisDoc#78]
Tried to pull the image down tonight, appears that it is not available?
```
docker pull redislabs/redisjson2:latest
Error response from daemon: manifest for redislabs/redisjson2:latest not found
```
**redislabs/redisjson2:edge** appears to work.  Maybe just a documentation or tagging issue?

**Comment by gkorland** [comment]
Please try
```
docker pull redislabs/redisjson2:edge
```

**Comment by gkorland** [comment]
`docker pull redislabs/redisjson2:latest` is also available now
